# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifierWindow(object):
    def setupUi(self, ClassifierWindow):
        ClassifierWindow.setObjectName("ClassifierWindow")
        ClassifierWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ClassifierWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 150, 81, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.threshold = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.threshold.setGeometry(QtCore.QRect(300, 150, 91, 31))
        self.threshold.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.threshold.setPlaceholderText("")
        self.threshold.setObjectName("threshold")
        self.OK = QtWidgets.QPushButton(self.centralwidget)
        self.OK.setGeometry(QtCore.QRect(540, 200, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")
        self.hto_tags = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.hto_tags.setGeometry(QtCore.QRect(300, 200, 171, 31))
        self.hto_tags.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_tags.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_tags.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.hto_tags.setPlainText("")
        self.hto_tags.setPlaceholderText("")
        self.hto_tags.setObjectName("hto_tags")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 181, 31))
        self.label_3.setObjectName("label_3")
        ClassifierWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClassifierWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        ClassifierWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClassifierWindow)
        self.statusbar.setObjectName("statusbar")
        ClassifierWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClassifierWindow)
        QtCore.QMetaObject.connectSlotsByName(ClassifierWindow)

    def retranslateUi(self, ClassifierWindow):
        _translate = QtCore.QCoreApplication.translate
        ClassifierWindow.setWindowTitle(_translate("ClassifierWindow", "Classifier Options"))
        self.label_7.setText(_translate("ClassifierWindow", "Threshold"))
        self.threshold.setToolTip(_translate("ClassifierWindow", "default: 0.8"))
        self.threshold.setPlainText(_translate("ClassifierWindow", "0.8"))
        self.OK.setText(_translate("ClassifierWindow", "OK"))
        self.hto_tags.setToolTip(_translate("ClassifierWindow", "HTO_1+HTO_2"))
        self.label_3.setText(_translate("ClassifierWindow", "HTO tag(s) to extract"))
