# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifierDialog(object):
    def setupUi(self, ClassifierDialog):
        ClassifierDialog.setObjectName("ClassifierDialog")
        ClassifierDialog.resize(320, 240)
        self.hto_tags = QtWidgets.QPlainTextEdit(ClassifierDialog)
        self.hto_tags.setGeometry(QtCore.QRect(10, 120, 291, 31))
        self.hto_tags.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_tags.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_tags.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.hto_tags.setPlainText("")
        self.hto_tags.setPlaceholderText("")
        self.hto_tags.setObjectName("hto_tags")
        self.label_3 = QtWidgets.QLabel(ClassifierDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 301, 51))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.threshold = QtWidgets.QPlainTextEdit(ClassifierDialog)
        self.threshold.setGeometry(QtCore.QRect(210, 10, 91, 31))
        self.threshold.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.threshold.setPlaceholderText("")
        self.threshold.setObjectName("threshold")
        self.label_8 = QtWidgets.QLabel(ClassifierDialog)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.OK = QtWidgets.QPushButton(ClassifierDialog)
        self.OK.setGeometry(QtCore.QRect(220, 190, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")

        self.retranslateUi(ClassifierDialog)
        QtCore.QMetaObject.connectSlotsByName(ClassifierDialog)

    def retranslateUi(self, ClassifierDialog):
        _translate = QtCore.QCoreApplication.translate
        ClassifierDialog.setWindowTitle(_translate("ClassifierDialog", "Classifier Options"))
        self.hto_tags.setToolTip(_translate("ClassifierDialog", "HTO_1+HTO_2"))
        self.label_3.setText(_translate("ClassifierDialog", "HTO tag(s) to extract, separated  by a comma (,):"))
        self.threshold.setToolTip(_translate("ClassifierDialog", "default: 0.8"))
        self.threshold.setPlainText(_translate("ClassifierDialog", "0.8"))
        self.label_8.setText(_translate("ClassifierDialog", "Threshold"))
        self.OK.setText(_translate("ClassifierDialog", "OK"))
