# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'estimator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EstimatorDialog(object):
    def setupUi(self, EstimatorDialog):
        EstimatorDialog.setObjectName("EstimatorDialog")
        EstimatorDialog.resize(320, 240)
        self.estimated_total_cell_num = QtWidgets.QPlainTextEdit(EstimatorDialog)
        self.estimated_total_cell_num.setGeometry(QtCore.QRect(10, 120, 91, 31))
        self.estimated_total_cell_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.estimated_total_cell_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.estimated_total_cell_num.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.estimated_total_cell_num.setPlaceholderText("")
        self.estimated_total_cell_num.setObjectName("estimated_total_cell_num")
        self.label_7 = QtWidgets.QLabel(EstimatorDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 301, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.OK = QtWidgets.QPushButton(EstimatorDialog)
        self.OK.setGeometry(QtCore.QRect(220, 190, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")

        self.retranslateUi(EstimatorDialog)
        QtCore.QMetaObject.connectSlotsByName(EstimatorDialog)

    def retranslateUi(self, EstimatorDialog):
        _translate = QtCore.QCoreApplication.translate
        EstimatorDialog.setWindowTitle(_translate("EstimatorDialog", "Estimator Options"))
        self.estimated_total_cell_num.setToolTip(_translate("EstimatorDialog", "default: 0.8"))
        self.estimated_total_cell_num.setPlainText(_translate("EstimatorDialog", "35685"))
        self.label_7.setText(_translate("EstimatorDialog", "Estimated total number of cells:"))
        self.OK.setText(_translate("EstimatorDialog", "OK"))
