# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'htoInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HtoWindow(object):
    def setupUi(self, HtoWindow):
        HtoWindow.setObjectName("HtoWindow")
        HtoWindow.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(HtoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hto_array = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.hto_array.setGeometry(QtCore.QRect(10, 70, 291, 31))
        self.hto_array.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_array.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_array.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.hto_array.setPlaceholderText("")
        self.hto_array.setObjectName("hto_array")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.OK = QtWidgets.QPushButton(self.centralwidget)
        self.OK.setGeometry(QtCore.QRect(220, 140, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")
        HtoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HtoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 28))
        self.menubar.setObjectName("menubar")
        HtoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HtoWindow)
        self.statusbar.setObjectName("statusbar")
        HtoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HtoWindow)
        QtCore.QMetaObject.connectSlotsByName(HtoWindow)

    def retranslateUi(self, HtoWindow):
        _translate = QtCore.QCoreApplication.translate
        HtoWindow.setWindowTitle(_translate("HtoWindow", "Options"))
        self.hto_array.setToolTip(_translate("HtoWindow", "HTO_1,HTO_2,HTO_3,HTO_4"))
        self.hto_array.setPlainText(_translate("HtoWindow", "HTO_1,HTO_2,HTO_3,HTO_4"))
        self.label.setText(_translate("HtoWindow", "Please input names of HTO, separated by a comma (,):"))
        self.OK.setText(_translate("HtoWindow", "OK"))
