# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'htoInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HtoDialog(object):
    def setupUi(self, HtoDialog):
        HtoDialog.setObjectName("HtoDialog")
        HtoDialog.resize(320, 240)
        self.hto_array = QtWidgets.QPlainTextEdit(HtoDialog)
        self.hto_array.setGeometry(QtCore.QRect(10, 100, 291, 31))
        self.hto_array.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_array.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hto_array.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.hto_array.setPlaceholderText("")
        self.hto_array.setObjectName("hto_array")
        self.label = QtWidgets.QLabel(HtoDialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 291, 51))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.OK = QtWidgets.QPushButton(HtoDialog)
        self.OK.setGeometry(QtCore.QRect(220, 190, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")

        self.retranslateUi(HtoDialog)
        QtCore.QMetaObject.connectSlotsByName(HtoDialog)

    def retranslateUi(self, HtoDialog):
        _translate = QtCore.QCoreApplication.translate
        HtoDialog.setWindowTitle(_translate("HtoDialog", "Options"))
        self.hto_array.setToolTip(_translate("HtoDialog", "HTO_1,HTO_2,HTO_3,HTO_4"))
        self.hto_array.setPlainText(_translate("HtoDialog", "HTO_1,HTO_2,HTO_3,HTO_4"))
        self.label.setText(_translate("HtoDialog", "Please input names of HTO, separated by a comma (,):"))
        self.OK.setText(_translate("HtoDialog", "OK"))
