# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/xml/classifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifierDialog(object):
    def setupUi(self, ClassifierDialog):
        ClassifierDialog.setObjectName("ClassifierDialog")
        ClassifierDialog.resize(449, 468)
        self.label_3 = QtWidgets.QLabel(ClassifierDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 431, 71))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.threshold = QtWidgets.QPlainTextEdit(ClassifierDialog)
        self.threshold.setGeometry(QtCore.QRect(140, 10, 91, 31))
        self.threshold.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.threshold.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.threshold.setPlaceholderText("")
        self.threshold.setObjectName("threshold")
        self.label_8 = QtWidgets.QLabel(ClassifierDialog)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.OK = QtWidgets.QPushButton(ClassifierDialog)
        self.OK.setGeometry(QtCore.QRect(350, 420, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")
        self.hto_tags_selection = QtWidgets.QListWidget(ClassifierDialog)
        self.hto_tags_selection.setGeometry(QtCore.QRect(10, 170, 171, 241))
        self.hto_tags_selection.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hto_tags_selection.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hto_tags_selection.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hto_tags_selection.setObjectName("hto_tags_selection")
        self.hto_tags = QtWidgets.QListWidget(ClassifierDialog)
        self.hto_tags.setGeometry(QtCore.QRect(260, 170, 171, 241))
        self.hto_tags.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hto_tags.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hto_tags.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hto_tags.setObjectName("hto_tags")
        self.add = QtWidgets.QPushButton(ClassifierDialog)
        self.add.setGeometry(QtCore.QRect(200, 210, 41, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setObjectName("add")
        self.remove = QtWidgets.QPushButton(ClassifierDialog)
        self.remove.setGeometry(QtCore.QRect(200, 250, 41, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove.sizePolicy().hasHeightForWidth())
        self.remove.setSizePolicy(sizePolicy)
        self.remove.setObjectName("remove")
        self.threshold_err_label = QtWidgets.QLabel(ClassifierDialog)
        self.threshold_err_label.setEnabled(True)
        self.threshold_err_label.setGeometry(QtCore.QRect(10, 50, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshold_err_label.setFont(font)
        self.threshold_err_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.threshold_err_label.setObjectName("threshold_err_label")

        self.retranslateUi(ClassifierDialog)
        QtCore.QMetaObject.connectSlotsByName(ClassifierDialog)

    def retranslateUi(self, ClassifierDialog):
        _translate = QtCore.QCoreApplication.translate
        ClassifierDialog.setWindowTitle(_translate("ClassifierDialog", "Classifier Options"))
        self.label_3.setText(_translate("ClassifierDialog", "Select HTO tag(s) to extract (default none).\n"
"If you want to run SSM rate estimator, please skip this."))
        self.threshold.setToolTip(_translate("ClassifierDialog", "default: 0.8"))
        self.threshold.setPlainText(_translate("ClassifierDialog", "0.8"))
        self.label_8.setText(_translate("ClassifierDialog", "Threshold"))
        self.OK.setText(_translate("ClassifierDialog", "OK"))
        self.add.setText(_translate("ClassifierDialog", "+"))
        self.remove.setText(_translate("ClassifierDialog", "-"))
        self.threshold_err_label.setText(_translate("ClassifierDialog", "Threshold should be a valid number between 0 and 1."))
