# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdfPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PdfPlotDialog(object):
    def setupUi(self, PdfPlotDialog):
        PdfPlotDialog.setObjectName("PdfPlotDialog")
        PdfPlotDialog.resize(320, 240)
        self.label_21 = QtWidgets.QLabel(PdfPlotDialog)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 301, 31))
        self.label_21.setObjectName("label_21")
        self.hto_to_plot = QtWidgets.QComboBox(PdfPlotDialog)
        self.hto_to_plot.setGeometry(QtCore.QRect(10, 100, 125, 36))
        self.hto_to_plot.setCurrentText("")
        self.hto_to_plot.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.hto_to_plot.setObjectName("hto_to_plot")
        self.OK = QtWidgets.QPushButton(PdfPlotDialog)
        self.OK.setGeometry(QtCore.QRect(220, 190, 80, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setObjectName("OK")

        self.retranslateUi(PdfPlotDialog)
        self.hto_to_plot.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PdfPlotDialog)

    def retranslateUi(self, PdfPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        PdfPlotDialog.setWindowTitle(_translate("PdfPlotDialog", "PDF Plot Options"))
        self.label_21.setText(_translate("PdfPlotDialog", "Select a HTO type to plot with:"))
        self.OK.setText(_translate("PdfPlotDialog", "OK"))
